### ISSUE TITLE
Unable to download starter

### ISSUE THREAD

**Issue by brianoh** [yazdanctx/react-fcc-forms#1]
The download link for starter appears to download the finished app, not the starter.

**Comment by yazdanctx** [comment]
Hello Brianoh

I've just downloaded the starter files and it was just fine.

Make sure to switch to `starter` branch before downloading the ZIP file. The `main` branch contains the completed version.

Or if you're cloning the repo, you can simply follow the instruction in the README file in order to get access to `starter` branch.
